const photographers = 
[
    {
        "name": "Mimi Keel",
        "id": 243,
        "city": "London",
        "country": "UK",
        "tags": ["portrait", "events", "travel", "animals"],
        "tagline": "Voir le beau dans le quotidien",
        "price": 400,
        "portrait": "MimiKeel.jpg",
        "photo": "./img/Mimi/Portrait_Nora.jpg",
        "alt-description": "thumbnail image of Mimi Keel"
    },
    {
        "name": "Ellie-Rose Wilkens",
        "id": 930,
        "city": "Paris",
        "country": "France",
        "tags": ["sports", "architecture"],
        "tagline": "Capturer des compositions complexes",
        "price": 250,
        "portrait": "EllieRoseWilkens.jpg",
        "photo": "./img/EllieRose/Architecture_Horseshoe.jpg",
        "alt-description": "thumbnail image of Ellie-Rose Wilkens"
    },
    {
        "name": "Tracy Galindo",
        "id": 82,
        "city": "Montreal",
        "country": "Canada",
        "tags": ["art", "fashion", "events"],
        "tagline": "Photographe freelance",
        "price": 500,
        "portrait": "TracyGalindo.jpg",
        "photo": "./img/Tracy/Fashion_Urban_Jungle.jpg",
        "alt-description": "thumbnail image of Tracy Galindo"
    },
    {
        "name": "Nabeel Bradford",
        "id": 527,
        "city": "Mexico City",
        "country": "Mexico",
        "tags": ["travel", "portrait"],
        "tagline": "Toujours aller de l'avant",
        "price": 350,
        "portrait": "NabeelBradford.jpg",
        "photo": "./img/Nabeel/Travel_Outdoor_Baths.jpg",
        "alt-description": "thumbnail image of Nabeel Bradford"
    },
    {
        "name": "Rhode Dubois",
        "id": 925,
        "city": "Barcelona",
        "country": "Spain",
        "tags": ["sport", "fashion", "events", "animals"],
        "tagline": "Je crée des souvenirs",
        "price": 275,
        "portrait": "RhodeDubois.jpg",
        "photo": "./img/Rhode/Fashion_Melody_Red_on_Stripes.jpg",
        "alt-description": "thumbnail image of Rhode Dubois"
    },
    {
        "name": "Marcel Nikolic",
        "id": 195,
        "city": "Berlin",
        "country": "Germany",
        "tags": ["travel", "architecture"],
        "tagline": "Toujours à la recherche de LA photo",
        "price": 300,
        "portrait": "MarcelNikolic.jpg",
        "photo": "./img/Marcel/Travel_Tower.jpg",
        "alt-description": "thumbnail image of Marcel Nikolic"
    }
]

const media =  
[
    {
        "id": 342550,
        "photographerId": 82,
        "title": "Fashion Yellow Beach",
        "image": "Fashion_Yellow_Beach.jpg",
        "tags": ["fashion"],
        "likes": 62,
        "date": "2011-12-08",
        "price": 55,
        "alt-description": "a young beautiful lady in yellow is standing on the beach"
    },
    {
        "id": 8520927,
        "photographerId": 82,
        "title": "Fashion Urban Jungle",
        "image": "Fashion_Urban_Jungle.jpg",
        "tags": ["fashion"],
        "likes": 11,
        "date": "2011-11-06",
        "price": 55,
        "alt-description": "a blonde lady is in the middle of the street in the urban city."
    },
    {
        "id": 9025895,
        "photographerId": 82,
        "title": "Fashion Pattern on a Pattern",
        "image": "Fashion_Pattern_on_Pattern.jpg",
        "tags": ["fashion"],
        "likes": 72,
        "date": "2013-08-12",
        "price": 55,
        "alt-description": "a blonde lady is in the middle of the street in the urban city"
    },
    {
        "id": 9275938,
        "photographerId": 82,
        "title": "Wedding Gazebo",
        "image": "Event_WeddingGazebo.jpg",
        "tags": ["events"],
        "likes": 69,
        "date": "2018-02-22",
        "price": 55,
        "alt-description": "a nicely decorated wedding venue with flowers without attendees"
    },
    {
        "id": 2053494,
        "photographerId": 82,
        "title": "Sparkles",
        "image": "Event_Sparklers.jpg",
        "tags": ["events"],
        "likes": 2,
        "date": "2020-05-25",
        "price": 55,
        "alt-description": "the back views of a couple looking at sparkles which others are holding in their hands"
    },
    {
        "id": 7324238,
        "photographerId": 82,
        "title": "18th Anniversary",
        "image": "Event_18thAnniversary.jpg",
        "tags": ["events"],
        "likes": 33,
        "date": "2019-06-12",
        "price": 55,
        "alt-description": "a party venue for someone's 18th birthday"
    },
    {
        "id": 8328953,
        "photographerId": 82,
        "title": "Wooden Horse Sculpture",
        "video": "Art_Wooden_Horse_Sculpture.mp4",
        "tags": ["art"],
        "likes": 24,
        "date": "2011-12-08",
        "price": 100
    },
    {
        "id": 7502053,
        "photographerId": 82,
        "title": "Triangle Man",
        "image": "Art_Triangle_Man.jpg",
        "tags": ["art"],
        "likes": 88,
        "date": "2007-05-07",
        "price": 55,
        "alt-description": "an art paiting of a man with triangle shape"
    },
    {
        "id": 8523492,
        "photographerId": 82,
        "title": "Purple Tunnel",
        "image": "Art_Purple_light.jpg",
        "tags": ["art"],
        "likes": 24,
        "date": "2018-05-05",
        "price": 55,
        "alt-description": "a tunnel with purple light"
    },
    {
        "id": 75902334,
        "photographerId": 82,
        "title": "Art Mine",
        "image": "Art_Mine.jpg",
        "tags": ["art"],
        "likes": 75,
        "date": "2019-11-25",
        "price": 55,
        "alt-description": "a bunch of red bird and blue bird"
    },

    {
        "id": 73852953,
        "photographerId": 925,
        "title": "8 Rows",
        "image": "Sport_2000_with_8.jpg",
        "tags": ["sport"],
        "likes": 52,
        "date": "2013-02-30",
        "price": 70,
        "alt-description": "people are on the vessel with oars"
    },
    {
        "id": 92758372,
        "photographerId": 925,
        "title": "Fashion Wings",
        "image": "Fashion_Wings.jpg",
        "tags": ["fashion"],
        "likes": 58,
        "date": "2018-07-17",
        "price": 70,
        "alt-description": "a man and a woman are raising one hand with their eyes closed"
    },
    {
        "id": 32958383,
        "photographerId": 925,
        "title": "Melody Red on Stripes",
        "image": "Fashion_Melody_Red_on_Stripes.jpg",
        "tags": ["fashion"],
        "likes": 11,
        "date": "2019-08-12",
        "price": 70,
        "alt-description": "a black woman in a red dress is standing on the stairs "
    },
    {
        "id": 928587383,
        "photographerId": 925,
        "title": "Venture Conference",
        "image": "Event_VentureConference.jpg",
        "tags": ["events"],
        "likes": 2,
        "date": "2019-01-02",
        "price": 70,
        "alt-description": "people are having a meeting in the office"
    },
    {
        "id": 725639493,
        "photographerId": 925,
        "title": "Product Pitch",
        "image": "Event_ProductPitch.jpg",
        "tags": ["events"],
        "likes": 3,
        "date": "2019-05-20",
        "price": 70,
        "alt-description": "a man is doing a presentaion in front of the audience"
    },
    {
        "id": 23394384,
        "photographerId": 925,
        "title": "Musical Festival Keyboard",
        "image": "Event_KeyboardCheck.jpg",
        "tags": ["events"],
        "likes": 52,
        "date": "2019-07-18",
        "price": 70,
        "alt-description": "a man is checking the keyboard of a Musical instrument"
    },
    {
        "id": 87367293,
        "photographerId": 925,
        "title": "Musical Festival Singer",
        "image": "Event_Emcee.jpg",
        "tags": ["events"],
        "likes": 23,
        "date": "2018-02-22",
        "price": 70,
        "alt-description": "a female singer is singing on the stage"
    },
    {
        "id": 593834784,
        "photographerId": 925,
        "title": "Animal Majesty",
        "image": "Animals_Majesty.jpg",
        "tags": ["animals"],
        "likes": 52,
        "date": "2017-03-13",
        "price": 70,
        "alt-description": "a wild large‐horned deer"
    },
    {
        "id": 83958935,
        "photographerId": 925,
        "title": "Cute Puppy on Sunset",
        "video": "Animals_Puppiness.mp4",
        "tags": ["animals"],
        "likes": 52,
        "date": "2016-06-12",
        "price": 70
    },

    {
        "id": 394583434,
        "photographerId": 527,
        "title": "Rock Mountains",
        "video": "Travel_Rock_Mountains.mp4",
        "tags": ["travel"],
        "likes": 23,
        "date": "2017-03-18",
        "price": 45
    },
    {
        "id": 343423425,
        "photographerId": 527,
        "title": "Outdoor Baths",
        "image": "Travel_Outdoor_Baths.jpg",
        "tags": ["travel"],
        "likes": 101,
        "date": "2017-04-03",
        "price": 45,
        "alt-description": "people are enjoying their time on the hot spring"
    },
    {
        "id": 73434243,
        "photographerId": 527,
        "title": "Road into the Hill",
        "image": "Travel_Road_into_Hill.jpg",
        "tags": ["travel"],
        "likes": 99,
        "date": "2018-04-30",
        "price": 45,
        "alt-description": "a lomg mountain road without any cars or people"
    },
    {
        "id": 23425523,
        "photographerId": 527,
        "title": "Bridge into the Forest",
        "image": "Travel_Bridge_into_Forest.jpg",
        "tags": ["travel"],
        "likes": 34,
        "date": "2016-04-05",
        "price": 45,
        "alt-description": "a bridge leads to the forest"
    },
    {
        "id": 23134513,
        "photographerId": 527,
        "title": "Boat Wonderer",
        "image": "Travel_Boat_Wanderer.jpg",
        "tags": ["travel"],
        "likes": 23,
        "date": "2017-03-18",
        "price": 45,
        "alt-description": "a boat is inside the breathtaking view of mountains and river"
    },
    {
        "id": 92352352,
        "photographerId": 527,
        "title": "Portrait Sunkiss",
        "image": "Portrait_Sunkissed.jpg",
        "tags": ["portrait"],
        "likes": 66,
        "date": "2018-05-24",
        "price": 45,
        "alt-description": "portrait of a red hair lady smiling"
    },
    {
        "id": 34513453,
        "photographerId": 527,
        "title": "Shaw Potrait",
        "image": "Portrait_Shaw.jpg",
        "tags": ["portait"],
        "likes": 52,
        "date": "2017-04-21",
        "price": 45,
        "alt-description": "monochrome portrait of a man"
    },
    {
        "id": 23523533,
        "photographerId": 527,
        "title": "Alexandra",
        "image": "Portrait_Alexandra.jpg",
        "tags": ["portait"],
        "likes": 95,
        "date": "2018-11-02",
        "price": 45,
        "alt-description": "monochrome portrait of a black woman with short hair "
    },
    {
        "id": 525834234,
        "photographerId": 527,
        "title": "Afternoon Break",
        "image": "Portrait_AfternoonBreak.jpg",
        "tags": ["portait"],
        "likes": 25,
        "date": "2019-01-02",
        "price": 45,
        "alt-description": "monochrome portrait of a black woman with short hair "
    },

    {
        "id": 623534343,
        "photographerId": 243,
        "title": "Lonesome",
        "image": "Travel_Lonesome.jpg",
        "tags": ["travel"],
        "likes": 88,
        "date": "2019-02-03",
        "price": 45,
        "alt-description": "a lady is in the middle of mountains"
    },
    {
        "id": 625025343,
        "photographerId": 243,
        "title": "Hillside Color",
        "image": "Travel_HillsideColor.jpg",
        "tags": ["travel"],
        "likes": 85,
        "date": "2019-04-03",
        "price": 45,
        "alt-description": "a bunch of colorful buildings near a cliff"
    },
    {
        "id": 2525345343,
        "photographerId": 243,
        "title": "Wednesday Potrait",
        "image": "Portrait_Wednesday.jpg",
        "tags": ["portait"],
        "likes": 34,
        "date": "2019-04-07",
        "price": 45,
        "alt-description": "a portrait of a little girl having a funny face"
    },
    {
        "id": 2523434634,
        "photographerId": 243,
        "title": "Nora Portrait",
        "image": "Portrait_Nora.jpg",
        "tags": ["portait"],
        "likes": 63,
        "date": "2019-04-07",
        "price": 45,
        "alt-description": "a portrait of a black girl with glasses"
    },
    {
        "id": 398847109,
        "photographerId": 243,
        "title": "Raw Black Portrait",
        "image": "Portrait_Background.jpg",
        "tags": ["portait"],
        "likes": 55,
        "date": "2019-06-20",
        "price": 45,
        "alt-description": "a monochrome portrait of a woman"
    },
    {
        "id": 2534342,
        "photographerId": 243,
        "title": "Seaside Wedding",
        "image": "Event_SeasideWedding.jpg",
        "tags": ["events"],
        "likes": 25,
        "date": "2019-06-21",
        "price": 45,
        "alt-description": "a seaside wedding venue"
    },
    {
        "id": 65235234,
        "photographerId": 243,
        "title": "Boulder Wedding",
        "image": "Event_PintoWedding.jpg",
        "tags": ["events"],
        "likes": 52,
        "date": "2019-06-25",
        "price": 45,
        "alt-description": "a bridal couple are gazing at each other under the sunshine"
    },
    {
        "id": 23523434,
        "photographerId": 243,
        "title": "Benevides Wedding",
        "image": "Event_BenevidesWedding.jpg",
        "tags": ["events"],
        "likes": 77,
        "date": "2019-06-28",
        "price": 45,
        "alt-description": "a bridal couple are gazing at each other at a wedding venue"
    },
    {
        "id": 5234343,
        "photographerId": 243,
        "title": "Wild Horses in the Mountains",
        "video": "Animals_Wild_Horses_in_the_mountains.mp4",
        "tags": ["animals"],
        "likes": 142,
        "date": "2019-08-23",
        "price": 60
    },
    {
        "id": 95234343,
        "photographerId": 243,
        "title": "Rainbow Bird",
        "image": "Animals_Rainbow.jpg",
        "tags": ["animals"],
        "likes": 59,
        "date": "2019-07-02",
        "price": 60,
        "alt-description": "a colorful bird is sitting on a branch"
    },

    {
        "id": 52343416,
        "photographerId": 195,
        "title": "Japanese Tower, Kyoto",
        "image": "Travel_Tower.jpg",
        "tags": ["travel"],
        "likes": 25,
        "date": "2019-04-03",
        "price": 60,
        "alt-description": "two lady are wearing Japanese traditional outfits and stading on the street in Kyoto"
    },
    {
        "id": 2523434,
        "photographerId": 195,
        "title": "Senset on Canals, Venice",
        "image": "Travel_SunsetonCanals.jpg",
        "tags": ["travel"],
        "likes": 53,
        "date": "2019-05-06",
        "price": 60,
        "alt-description": "a scenery of a canal at sunset"
    },
    {
        "id": 95293534,
        "photographerId": 195,
        "title": "Mountain and Lake",
        "image": "Travel_OpenMountain.jpg",
        "tags": ["travel"],
        "likes": 33,
        "date": "2019-05-12",
        "price": 60,
        "alt-description": "a scenery of mountains and a lake"
    },
    {
        "id": 356234343,
        "photographerId": 195,
        "title": "City Bike and Stair, Paris",
        "image": "Travel_Bike_and_Stair.jpg",
        "tags": ["travel"],
        "likes": 53,
        "date": "2019-06-20",
        "price": 60,
        "alt-description": "a nice building and a bicycle in a city"
    },
    {
        "id": 235234343,
        "photographerId": 195,
        "title": "Adventure Door, India",
        "image": "Travel_Adventure_Door.jpg",
        "tags": ["travel"],
        "likes": 63,
        "date": "2019-06-26",
        "price": 60,
        "alt-description": "a door of a traditional building in India"
    },
    {
        "id": 6234234343,
        "photographerId": 195,
        "title": "Contrast, St Petersburg",
        "image": "Architecture_Contrast.jpg",
        "tags": ["architecture"],
        "likes": 52,
        "date": "2019-06-30",
        "price": 60,
        "alt-description": "a historical structures with blue sky"
    },
    {
        "id": 6525666253,
        "photographerId": 195,
        "title": "On a Hill, Tibet",
        "image": "Architecture_On_a_hill.jpg",
        "tags": ["architecture"],
        "likes": 63,
        "date": "2019-07-20",
        "price": 60,
        "alt-description": "a collection of white color buildings in the middle of mountains"
    },
    {
        "id": 98252523433,
        "photographerId": 195,
        "title": "Leaning Tower, Pisa",
        "image": "Architecture_Dome.jpg",
        "tags": ["architecture"],
        "likes": 88,
        "date": "2020-01-05",
        "price": 60,
        "alt-description": "a leaning tower"
    },
    {
        "id": 9259398453,
        "photographerId": 195,
        "title": "Circle Highways, Buenos Aires",
        "video": "Architecture_coverr_circle_empty_highway_in_buenos_aires_587740985637.mp4",
        "tags": ["architecture"],
        "likes": 57,
        "date": "2020-01-20",
        "price": 65
    },
    {
        "id": 3523523534,
        "photographerId": 195,
        "title": "Corner Building and Blue Sky",
        "image": "Architecture_Corner_Room.jpg",
        "tags": ["architecture"],
        "likes": 54,
        "date": "2020-05-05",
        "price": 60,
        "alt-description": "a corner of a beautiful building"
    },

    {
        "id": 952343423,
        "photographerId": 930,
        "title": "Tricks in the Air",
        "video": "Sport_Tricks_in_the_air.mp4",
        "tags": ["sport"],
        "likes": 150,
        "date": "2018-02-30",
        "price": 70
    },
    {
        "id": 235234343,
        "photographerId": 930,
        "title": "Climber",
        "image": "Sport_Next_Hold.jpg",
        "tags": ["sport"],
        "likes": 101,
        "date": "2018-03-05",
        "price": 65,
        "alt-description": "a lady doing rock climing"
    },
    {
        "id": 235343222,
        "photographerId": 930,
        "title": "Surfer",
        "image": "sport_water_tunnel.jpg",
        "tags": ["sport"],
        "likes": 103,
        "date": "2018-03-10",
        "price": 70,
        "alt-description": "a person is surfing"
    },
    {
        "id": 7775342343,
        "photographerId": 930,
        "title": "Skier",
        "image": "Sport_Sky_Cross.jpg",
        "tags": ["sport"],
        "likes": 77,
        "date": "2018-04-16",
        "price": 50,
        "alt-description": "a person is skiing"
    },
    {
        "id": 9253445784,
        "photographerId": 930,
        "title": "Race End",
        "image": "Sport_Race_End.jpg",
        "tags": ["sport"],
        "likes": 88,
        "date": "2018-04-22",
        "price": 65,
        "alt-description": "Sprint running races of women"
    },
    {
        "id": 22299394,
        "photographerId": 930,
        "title": "Jump!",
        "image": "Sport_Jump.jpg",
        "tags": ["sport"],
        "likes": 95,
        "date": "2018-04-27",
        "price": 70,
        "alt-description": "a guy is jumping from a skateboard"
    },
    {
        "id": 3452342633,
        "photographerId": 930,
        "title": "White Light",
        "image": "Architecture_White_Light.jpg",
        "tags": ["architecture"],
        "likes": 52,
        "date": "2018-05-03",
        "price": 75,
        "alt-description": "inside a modern white color building"
    },
    {
        "id": 939234243,
        "photographerId": 930,
        "title": "Water on Modern Building",
        "image": "Architecture_Water_on_Modern.jpg",
        "tags": ["architecture"],
        "likes": 55,
        "date": "2018-05-10",
        "price": 72,
        "alt-description": "a modern architecture with water"
    },
    {
        "id": 222959233,
        "photographerId": 930,
        "title": "Horseshoe",
        "image": "Architecture_Horseshoe.jpg",
        "tags": ["architecture"],
        "likes": 85,
        "date": "2018-05-15",
        "price": 71,
        "alt-description": "a monochrome architecture"
    },
    {
        "id": 965933434,
        "photographerId": 930,
        "title": "Cross Bar",
        "image": "Architecture_Cross_Bar.jpg",
        "tags": ["architecture"],
        "likes": 66,
        "date": "2018-05-20",
        "price": 58,
        "alt-description": "a modern architecture with white and yellow glass"
    },
    {
        "id": 777723343,
        "photographerId": 930,
        "title": "Connected Curves",
        "image": "Architecture_Connected_Curves.jpg",
        "tags": ["architecture"],
        "likes": 79,
        "date": "2018-05-21",
        "price": 80,
        "alt-description": "a connected part of two modern buildings"
    }
    ]